package input

type KeyCode int32

const (
	KEY_UNKNOWN       KeyCode = -1
	KEY_SPACE         KeyCode = 32
	KEY_APOSTROPHE    KeyCode = 39 /* ' */
	KEY_COMMA         KeyCode = 44 /* , */
	KEY_MINUS         KeyCode = 45 /* - */
	KEY_PERIOD        KeyCode = 46 /* . */
	KEY_SLASH         KeyCode = 47 /* / */
	KEY_0             KeyCode = 48
	KEY_1             KeyCode = 49
	KEY_2             KeyCode = 50
	KEY_3             KeyCode = 51
	KEY_4             KeyCode = 52
	KEY_5             KeyCode = 53
	KEY_6             KeyCode = 54
	KEY_7             KeyCode = 55
	KEY_8             KeyCode = 56
	KEY_9             KeyCode = 57
	KEY_SEMICOLON     KeyCode = 59 /* ; */
	KEY_EQUAL         KeyCode = 61 /* = */
	KEY_A             KeyCode = 65
	KEY_B             KeyCode = 66
	KEY_C             KeyCode = 67
	KEY_D             KeyCode = 68
	KEY_E             KeyCode = 69
	KEY_F             KeyCode = 70
	KEY_G             KeyCode = 71
	KEY_H             KeyCode = 72
	KEY_I             KeyCode = 73
	KEY_J             KeyCode = 74
	KEY_K             KeyCode = 75
	KEY_L             KeyCode = 76
	KEY_M             KeyCode = 77
	KEY_N             KeyCode = 78
	KEY_O             KeyCode = 79
	KEY_P             KeyCode = 80
	KEY_Q             KeyCode = 81
	KEY_R             KeyCode = 82
	KEY_S             KeyCode = 83
	KEY_T             KeyCode = 84
	KEY_U             KeyCode = 85
	KEY_V             KeyCode = 86
	KEY_W             KeyCode = 87
	KEY_X             KeyCode = 88
	KEY_Y             KeyCode = 89
	KEY_Z             KeyCode = 90
	KEY_LEFT_BRACKET  KeyCode = 91  /* [ */
	KEY_BACKSLASH     KeyCode = 92  /* \ */
	KEY_RIGHT_BRACKET KeyCode = 93  /* ] */
	KEY_GRAVE_ACCENT  KeyCode = 96  /* ` */
	KEY_WORLD_1       KeyCode = 161 /* non-US #1 */
	KEY_WORLD_2       KeyCode = 162 /* non-US #2 */
	KEY_ESCAPE        KeyCode = 256
	KEY_ENTER         KeyCode = 257
	KEY_TAB           KeyCode = 258
	KEY_BACKSPACE     KeyCode = 259
	KEY_INSERT        KeyCode = 260
	KEY_DELETE        KeyCode = 261
	KEY_RIGHT         KeyCode = 262
	KEY_LEFT          KeyCode = 263
	KEY_DOWN          KeyCode = 264
	KEY_UP            KeyCode = 265
	KEY_PAGE_UP       KeyCode = 266
	KEY_PAGE_DOWN     KeyCode = 267
	KEY_HOME          KeyCode = 268
	KEY_END           KeyCode = 269
	KEY_CAPS_LOCK     KeyCode = 280
	KEY_SCROLL_LOCK   KeyCode = 281
	KEY_NUM_LOCK      KeyCode = 282
	KEY_PRINT_SCREEN  KeyCode = 283
	KEY_PAUSE         KeyCode = 284
	KEY_F1            KeyCode = 290
	KEY_F2            KeyCode = 291
	KEY_F3            KeyCode = 292
	KEY_F4            KeyCode = 293
	KEY_F5            KeyCode = 294
	KEY_F6            KeyCode = 295
	KEY_F7            KeyCode = 296
	KEY_F8            KeyCode = 297
	KEY_F9            KeyCode = 298
	KEY_F10           KeyCode = 299
	KEY_F11           KeyCode = 300
	KEY_F12           KeyCode = 301
	KEY_F13           KeyCode = 302
	KEY_F14           KeyCode = 303
	KEY_F15           KeyCode = 304
	KEY_F16           KeyCode = 305
	KEY_F17           KeyCode = 306
	KEY_F18           KeyCode = 307
	KEY_F19           KeyCode = 308
	KEY_F20           KeyCode = 309
	KEY_F21           KeyCode = 310
	KEY_F22           KeyCode = 311
	KEY_F23           KeyCode = 312
	KEY_F24           KeyCode = 313
	KEY_F25           KeyCode = 314
	KEY_KP_0          KeyCode = 320
	KEY_KP_1          KeyCode = 321
	KEY_KP_2          KeyCode = 322
	KEY_KP_3          KeyCode = 323
	KEY_KP_4          KeyCode = 324
	KEY_KP_5          KeyCode = 325
	KEY_KP_6          KeyCode = 326
	KEY_KP_7          KeyCode = 327
	KEY_KP_8          KeyCode = 328
	KEY_KP_9          KeyCode = 329
	KEY_KP_DECIMAL    KeyCode = 330
	KEY_KP_DIVIDE     KeyCode = 331
	KEY_KP_MULTIPLY   KeyCode = 332
	KEY_KP_SUBTRACT   KeyCode = 333
	KEY_KP_ADD        KeyCode = 334
	KEY_KP_ENTER      KeyCode = 335
	KEY_KP_EQUAL      KeyCode = 336
	KEY_LEFT_SHIFT    KeyCode = 340
	KEY_LEFT_CONTROL  KeyCode = 341
	KEY_LEFT_ALT      KeyCode = 342
	KEY_LEFT_SUPER    KeyCode = 343
	KEY_RIGHT_SHIFT   KeyCode = 344
	KEY_RIGHT_CONTROL KeyCode = 345
	KEY_RIGHT_ALT     KeyCode = 346
	KEY_RIGHT_SUPER   KeyCode = 347
	KEY_MENU          KeyCode = 348
)

type MouseButton int32

const (
	MOUSE_BUTTON_1 MouseButton = 0
	MOUSE_BUTTON_2 MouseButton = 1
	MOUSE_BUTTON_3 MouseButton = 2
	MOUSE_BUTTON_4 MouseButton = 3
	MOUSE_BUTTON_5 MouseButton = 4
	MOUSE_BUTTON_6 MouseButton = 5
	MOUSE_BUTTON_7 MouseButton = 6
	MOUSE_BUTTON_8 MouseButton = 7
)